<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>xbd.ControlLib</RootNamespace>
    <AssemblyName>xbd.ControlLib</AssemblyName>
  </PropertyGroup>

</Project>
