<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.45.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.11" />
    <PackageReference Include="thinger.DataConvertLib" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\xbd.CommunicationLib\xbd.CommunicationLib.csproj" />
  </ItemGroup>

</Project>
