<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\*.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WinForms" Version="4.1.70" />
    <PackageReference Include="thinger.DataConvertLib" Version="4.0.1" />
    <PackageReference Include="MiniExcel" Version="1.45.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\xbd.ControlLib\xbd.ControlLib.csproj" />
    <ProjectReference Include="..\xbd.NodeSetting\xbd.NodeSetting.csproj" />
    <ProjectReference Include="..\xbd.WarehouseTHBLL\xbd.WarehouseTHBLL.csproj" />
    <ProjectReference Include="..\xbd.WarehouseTHDAL\xbd.WarehouseTHDAL.csproj" />
    <ProjectReference Include="..\xbd.WarehouseTHModels\xbd.WarehouseTHModels.csproj" />
    <ProjectReference Include="..\xbd.WarehouseTHUtils\xbd.WarehouseTHUtils.csproj" />
  </ItemGroup>

</Project>
